version: "3.7"
services:
  frontend:
    build:
      context: ./frontend
    container_name: node
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app:/home/node/app
    command: sh -c "cd /home/node/app && npm install && yarn start"
    environment:
      - NODE_ENV=development
    stdin_open: true
  backend:
    build:
      context: ./backend
    container_name: api
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    volumes:
        - ./backend/src:/app/src
